enum RegionType {
    Unknown=0,
    Scotland=1,
    England=2,
    Wales=3,
    NorthernIreland=4,
    IsleOfMan=5,
    Spain=6,
    France=7,
    Italy=8,
    USA=9,
    Canada=10,
    Mexico=11,
    Australia=12,
    NewZealand=13,
    Switzerland=14,
    Austria=15,
    Norway=16,
    Portugal=17,
    Greece=18,
    Morocco=19,
    // Jordan=20,
    // Nepal=21,
    // Brazil=22,
    // Argentina=23,
    // Chile=24,
    // Peru=25,
    // Ecuador=26,
    CostaRica=27,
    // Iceland=28,
    // Slovenia=29,
    // Croatia=30,
    // Germany=31,
    // China=32,
    // Japan=33,
}

export default RegionType;

export const RegionTypeList: RegionType[] = [
    RegionType.Unknown,
    RegionType.Scotland,
    RegionType.England,
    RegionType.Wales,
    RegionType.NorthernIreland,
    RegionType.IsleOfMan,
    RegionType.Spain,
    RegionType.France,
    RegionType.Italy,
    RegionType.USA,
    RegionType.Canada,
    RegionType.Mexico,
    RegionType.Australia,
    RegionType.NewZealand,
    RegionType.Switzerland,
    RegionType.Austria,
    RegionType.Norway,
    RegionType.Portugal,
    RegionType.Greece,
    RegionType.Morocco,
    // RegionType.Jordan,
    // RegionType.Nepal,
    // RegionType.Brazil,
    // RegionType.Argentina,
    // RegionType.Chile,
    // RegionType.Peru,
    // RegionType.Ecuador,
    RegionType.CostaRica,
    // RegionType.Iceland,
    // RegionType.Slovenia,
    // RegionType.Croatia,
    // RegionType.Germany,
    // RegionType.China,
    // RegionType.Japan
]