enum RegionType {
    Unknown=0,
    Scotland=1,
    England=2,
    Wales=3,
    NorthernIreland=4,
    IsleOfMan=5,
    Spain=6,
    France=7,
    Italy=8,
    USA=9,
    Canada=10,
    Mexico=11,
    Australia=12,
    NewZealand=13,
    Switzerland=14,
    Austria=15,
    Norway=16,
    Portugal=17,
    Greece=18,
    Morocco=19,
    // Jordan=20,
    Nepal=21,
    Brazil=22,
    Argentina=23,
    Chile=24,
    Peru=25,
    // Ecuador=26,
    CostaRica=27,
    Iceland=28,
    // Slovenia=29,
    // Croatia=30,
    Germany=31,
    China=32,
    Japan=33,
    Turkey=34,
    SouthAfrica=35,
}

export default RegionType;

export const RegionTypeList: RegionType[] = [
    RegionType.Unknown,
    RegionType.Argentina,
    RegionType.Australia,
    RegionType.Austria,
    RegionType.Brazil,
    RegionType.Canada,
    RegionType.Chile,
    RegionType.China,
    RegionType.CostaRica,
    RegionType.England,
    RegionType.France,
    RegionType.Germany,
    RegionType.Greece,
    RegionType.Iceland,
    RegionType.IsleOfMan,
    RegionType.Italy,
    RegionType.Japan,
    RegionType.Mexico,
    RegionType.Morocco,
    RegionType.Nepal,
    RegionType.NewZealand,
    RegionType.NorthernIreland,
    RegionType.Norway,
    RegionType.Peru,
    RegionType.Portugal,
    RegionType.Scotland,
    RegionType.SouthAfrica,
    RegionType.Spain,
    RegionType.Switzerland,
    RegionType.Turkey,
    RegionType.USA,
    RegionType.Wales,
    // RegionType.Jordan,
    // RegionType.Ecuador,
    // RegionType.Slovenia,
    // RegionType.Croatia,
]