ALTER TABLE Canyons ADD IsUnrated BIT DEFAULT 1;
ALTER TABLE Canyons ADD Region SMALLINT DEFAULT 0;
ALTER TABLE Canyons ADD CanyonType SMALLINT DEFAULT 0;
ALTER TABLE Canyons ADD IsDeleted BIT DEFAULT 0;